In [1]:
from google.colab import drive # Import a library named google.colab
drive.mount('/content/drive', force_remount=True) # mount the content to the directory `/content/drive`

Mounted at /content/drive


In [27]:
import numpy as np

###1. 创建numpy数组 </br>
1.1 使用列表创建numpy数组,然后将其转换为numpy数组。

In [10]:
my_list = [0,1,2,3]
my_array = np.array(my_list)
my_array

array([0, 1, 2, 3])

####1.2 使用内置函数创建numpy数组。
np.arange(begin,end,step)。终点不包括。

In [4]:
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

####1.3 使用内置函数创建numpy数组。
np.linspace(begin,end,cnt),创建线性均匀间隔的数组。终点包括。


In [6]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

####1.4 随机内置函数创建随机数组。
np.random.randint函数。它以起点，终点(数组中未包含)和形状的大小(不担心，稍后我们将对其进行研究)作为输入。

In [7]:
np.random.randint(1, 5, (3,3))

array([[4, 2, 3],
       [4, 4, 2],
       [4, 3, 4]])

使用随机数生成随机数组前，可以确定random使用的种子。使用np.random.seed()

In [9]:
np.random.seed(12)
array1 = np.random.randint(0, 10, 20)
array1

array([6, 1, 2, 3, 3, 0, 6, 1, 4, 5, 9, 2, 6, 0, 5, 8, 2, 9, 3, 4])

In [10]:
np.random.seed(12)
array2 = np.random.randint(0, 10, 20)
array2

array([6, 1, 2, 3, 3, 0, 6, 1, 4, 5, 9, 2, 6, 0, 5, 8, 2, 9, 3, 4])

####1.5 设置正态(高斯)分布的样本
如果我们需要高斯分布的样本，大小为100，均值为0，标准差为1，该怎么办？ 好吧，我们再次使用.random，但是这里我们使用.normal代替.randint！

In [11]:
np.random.seed(101)
norm_arr = np.random.normal(0, 1, 100)
norm_arr

array([ 2.70684984e+00,  6.28132709e-01,  9.07969446e-01,  5.03825754e-01,
        6.51117948e-01, -3.19318045e-01, -8.48076983e-01,  6.05965349e-01,
       -2.01816824e+00,  7.40122057e-01,  5.28813494e-01, -5.89000533e-01,
        1.88695309e-01, -7.58872056e-01, -9.33237216e-01,  9.55056509e-01,
        1.90794322e-01,  1.97875732e+00,  2.60596728e+00,  6.83508886e-01,
        3.02665449e-01,  1.69372293e+00, -1.70608593e+00, -1.15911942e+00,
       -1.34840721e-01,  3.90527843e-01,  1.66904636e-01,  1.84501859e-01,
        8.07705914e-01,  7.29596753e-02,  6.38787013e-01,  3.29646299e-01,
       -4.97104023e-01, -7.54069701e-01, -9.43406403e-01,  4.84751647e-01,
       -1.16773316e-01,  1.90175480e+00,  2.38126959e-01,  1.99665229e+00,
       -9.93263500e-01,  1.96799505e-01, -1.13664459e+00,  3.66479606e-04,
        1.02598415e+00, -1.56597904e-01, -3.15791439e-02,  6.49825833e-01,
        2.15484644e+00, -6.10258856e-01, -7.55325340e-01, -3.46418504e-01,
        1.47026771e-01, -

array.mean()求平均值，array.std()求标准差，array_min()求最小值，array_max()求最大值，array_sort()从小到大排序。

In [15]:
print("mean: ", norm_arr.mean())
print("std: ", norm_arr.std())
print("min: ", norm_arr.min())
print("max: ", norm_arr.max())
norm_arr.sort()
norm_arr

mean:  0.16636988042311196
std:  1.0338189430873386
min:  -2.1412122910809264
max:  2.706849839399938


array([-2.14121229e+00, -2.01816824e+00, -1.97260510e+00, -1.70608593e+00,
       -1.46751402e+00, -1.38292010e+00, -1.22308204e+00, -1.15911942e+00,
       -1.13664459e+00, -1.13381716e+00, -1.04677954e+00, -1.00518692e+00,
       -9.93263500e-01, -9.43406403e-01, -9.33237216e-01, -9.25874259e-01,
       -9.05099902e-01, -8.66885035e-01, -8.55196041e-01, -8.48076983e-01,
       -7.58872056e-01, -7.55325340e-01, -7.54069701e-01, -7.41789705e-01,
       -7.32845148e-01, -6.10258856e-01, -5.89000533e-01, -5.68581361e-01,
       -5.38234626e-01, -4.97104023e-01, -4.94095358e-01, -4.79448039e-01,
       -3.91156627e-01, -3.76518675e-01, -3.46418504e-01, -3.19318045e-01,
       -1.62534735e-01, -1.56597904e-01, -1.34840721e-01, -1.16773316e-01,
       -3.15791439e-02, -3.11604815e-02,  3.66479606e-04,  7.29596753e-02,
        1.47026771e-01,  1.66904636e-01,  1.84501859e-01,  1.87124522e-01,
        1.88695309e-01,  1.90794322e-01,  1.96799505e-01,  2.21490685e-01,
        2.30336344e-01,  

####1.6 检查数组的尺寸：arr.ndim()；检查数组的形状：arr.shape()
可通过下面的例子分别知道什么事尺寸和形状。

In [19]:
small_arr = np.array([1,2])
medium_arr = np.array([[1,2],[3,4],[5,6],[7,8]])
big_arr = np.array([[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]]])
print("small ndim: ", small_arr.ndim)
print("medium ndim: ", medium_arr.ndim)
print("big ndim: ", big_arr.ndim)
print("small shape: ", small_arr.shape)
print("medium shape: ", medium_arr.shape)
print("big shape: ", big_arr.shape)


small ndim:  1
medium ndim:  2
big ndim:  3
small shape:  (2,)
medium shape:  (4, 2)
big shape:  (3, 4, 2)


####1.7 创建零数组：np.zeros()
要创建一个在每个索引处都为零的数组，我们需要指定：数组的长度和形状(作为元组)。 如果未指定形状，则默认值为(数组的长度)。</br>
输出是浮点值为0的数组。

In [21]:
zero_arr1 = np.zeros(3)
zero_arr2 = np.zeros((3,2))
print(zero_arr1)
print(zero_arr2)

[0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


####1.8 创建一数组：np.ones()
与.zeros函数一样，此处适用相同的条件。要创建一个在每个索引处都有一个的数组，我们需要指定：数组的长度和形状(作为元组)。 如果未指定形状，则默认值为(数组的长度)。
</br>
输出是浮点数为1的数组。

In [22]:
one_arr1 = np.ones(3)
one_arr2 = np.ones((3,2))
print(one_arr1)
print(one_arr2)


[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


####1.9 创建全x数组: np.full()
O和1可能不是我们可能要使用的唯一数字。 如果我们想创建一个在每个索引处具有数字4的数组怎么办？ 我们可以完全使用full function。首先，我们指定数组的形状，然后指定每个索引处所需的数字。



In [23]:
np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

###2. 处理numpy数组
####2.1 算数运算

假设我们有两个形状和长度相同的数组，分别称为a和b 。我们可以：</br>
取相应索引的总和。</br>
在每个索引处添加元素值。</br>
这些对减、乘、除同样有效。

In [25]:
a = np.random.randint(0, 10, 3)
b = np.random.randint(0, 10, 3)
print(a)
print(b)
print(a + b) # addition of two arrays
print(a + 1) # adding 1 to each element of a

[2 8 9]
[6 6 9]
[ 8 14 18]
[ 3  9 10]


####2.2 重塑数组
假设我们有一个长度为9的数组。这里的目标是创建一个新数组，其中包含相同的数据，但是具有新的形状！ 让我们选择(3,3)形状。 我们可以使用reshape内置函数。

In [26]:
first_arr = np.arange(0,9)
print(first_arr)
sec_arr = first_arr.reshape(3,3)
print(sec_arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


####2.3 从数组访问特定元素
首先，考虑一个2维数组，该数组有5个嵌套数组，每个数组有5个元素。 您可以将此数组作为矩阵放在脑海中。</br>
输入mat [0]时，它代表第一个维度和第一个数组(因为0)。


In [28]:
mat = np.arange(0, 25).reshape(5, 5)
print(mat)
print(mat[0])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4]


mat[-1]获取矩阵最后一个数组。


In [29]:
mat[-1]

array([20, 21, 22, 23, 24])

现在，我们要从该矩阵中获取值0。 使用mat [0]，我们从第一个维度获得第一个数组。 现在使用mat [0,0]表示第二维的矩阵中的元素0。



In [30]:
mat[0,0]

0

获得第三列：当我们要访问所有元素时，我们可以使用符号：。 因此，这里我们说从第一个维度开始，我想要一切，从第二个维度开始，我只想要第三个元素。



In [31]:
mat[:, 2]

array([ 2,  7, 12, 17, 22])

获得第二排：从第一个维度开始只要第二个数组，从第二个维度开始，要一切。 将这两部分结合在一起，剩下第二排。



In [32]:
mat[1,:]

array([5, 6, 7, 8, 9])

获得切片：在这里，我们要获取矩阵的一部分。 假设我们想要一个3x3矩阵，其值位于原始矩阵的左上角。 我们可以这样做：



In [33]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

masking: 如果我们要指定一些限制，则遮罩很有用。 假设我们只希望矩阵中的值小于5。



In [34]:
mat < 5

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

masking中要获取实际值，而不是具有布尔值的数组，我们可以这样做：



In [38]:
my_filter = mat < 5
mat[my_filter]

array([0, 1, 2, 3, 4])