In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


###1. Tensor Constructor
from list/numPy array

In [2]:
import torch
import numpy as np
x = torch.tensor([[1,1],[2,2]])
y = torch.from_numpy(np.array([[1,1], [2,2]]))
print(x)
print(y)

tensor([[1, 1],
        [2, 2]])
tensor([[1, 1],
        [2, 2]])


zero tensor

In [3]:
torch.zeros([2,2])

tensor([[0., 0.],
        [0., 0.]])

unit tensor

In [4]:
torch.ones([2,2,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

###2. Tensor operators
Squeeze: remove the specified dimension with length 1. 

In [5]:
x = torch.zeros([1,2,3])
print(x)
print(x.shape)
x = x.squeeze(0) # remove dimension 0, cause dimension 0.length = 1
print(x)
print(x.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


unsqueeze: expand a new dimension.

In [6]:
x = torch.zeros([2,3])
x = x.unsqueeze(1)
print(x)
print(x.shape)

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])
torch.Size([2, 1, 3])


transpose: transpose two specified dimensions.(转置)

In [7]:
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)
print(x.shape)
x = x.transpose(0, 1)
print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


cat: concatenate multiple tensors.

In [8]:
x = torch.zeros([2,1,3])
y = torch.zeros([2,2,3])
z = torch.zeros([2,4,3])
w = torch.cat([x,y,z], dim=1)
w.shape

torch.Size([2, 7, 3])

addition</br>subtraction</br>power</br>summation</br>mean(input dtype should be either floating point or complex dtypes).

In [9]:
x = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
y = torch.tensor([[1,2,3],[4,5,6]])
z = x + y
print(z)
print(z.shape)
z = x - y
print(z)
print(z.shape)
z = pow(x, 2)
print(z)
print(z.shape)
z = x.sum()
print(z)
z = x.mean()
print(z)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
torch.Size([2, 3])
tensor(21.)
tensor(3.5000)


attributes.

In [10]:
x = torch.zeros([2,2])
print(x.shape)
print(x.dtype)

torch.Size([2, 2])
torch.float32


shape manipulation.

In [11]:
x = torch.zeros([2,2])
print(x.reshape([4]).shape)
print(x.view(-1,4).shape)

torch.Size([4])
torch.Size([1, 4])


###3. CPU or GPU

In [13]:
x = x.to('cpu')
x = x.to('cuda')
torch.cuda.is_available()

True

###4. Calculate Gradient


In [14]:
x = torch.tensor([[1.,0.],[-1.,1.]], requires_grad=True) # 1
z = x.pow(2).sum() # 2, object function
z.backward() # 3, calculate gradient and store them in x
x.grad

tensor([[ 2.,  0.],
        [-2.,  2.]])

###5. Overview of the DNN Training Procedure
####5.1 Load Data

In [15]:
from torch.utils.data import Dataset, DataLoader
class MyDataset(Dataset):
  def __init__(self, file):
    self.data = ...


  def __getitem__(self, index):
    return self.data[index]


  def __len__(self):
    return len(self.data)

In [16]:
dataset = MyDataset(file)
# shuffle is reading data disorderedly. Training is set true, testing is set false.
dataloader = DataLoader(dataset, batch_size, shuffle=True) 


NameError: ignored

####5.2 torch.nn -- Neural Network Layers
Linear layer(Fully-connected layer)

In [3]:
layer = torch.nn.Linear(32, 64) # can be any shape but the last dimension must be 32
print(layer.weight.shape)
print(layer.bias.shape)


torch.Size([64, 32])
torch.Size([64])


####5.3 torch.nn -- Activation Function
nn.Sigmoid(), nn.ReLU()

####5.4 torch.nn -- Loss Functions
Mean Square Error(for linear regression):</br>
nn.MSELoss()</br>
Cross entropy(for classification):</br>
nn.CrossEntropyLoss()

####5.5 torch.nn -- Build your own neural network

In [5]:
import torch.nn as nn
class MyModel(nn.Module):
  def __init__(self):
    super(MyModel, self).__init__()
    self.net == nn.Sequential(
        nn.Linear(10, 32),
        nn.Sigmoid(),
        nn.Linear(32,1)
    )
    
  
  def forward(self, x):
    return self.net(x)

####5.6 optimizer -- torch.optim
optimization algorithms for neural networks(gradient descent)</br>
Stochastic Gradient Descent(SGD):</br>
torch.optim.SGD(params, lr, momentum = 0) // lr = learning rate



####5.7 Nerual Network Training


In [1]:
dataset = MyDataset(file) # read data via dataset
tr_set = DataLoader(dataset, 16, shuffle=True) # put dataseet into DataLoader
model = MyModel().to(device) # construct model and move to device(cpu/cuda)
criterion = nn.MSELoss() # set loss function
optimizer = torch.optim.SGD(model.parameters(), 0.1) #set optimizer

NameError: ignored

In [ ]:
for epoch in range(n_epochs): # iterate n_epochs
  model.train() # set model to train mode
  for x, y in tr_set: # iterate through the dataLoader
      optimizer.zero_grad() # set gradient to zero
      x, y = x.to(device), y.to(device) # move data to device(cpu/cuda)
      pred = model(x) # forward pass(compute output)
      loss = criterion(pred, y) # compute loss
      loss.backward() # compute gradient(backpropagation)
      optimizer.step() # update model with optimizer


####5.7 Nerual Network Evaluation(Validation Set)

In [ ]:
model.eval() # set model to evaluation mode
total_loss = 0 
for x, y in dv_set: # iterate through the dataLoader
  x, y = x.to(device), y.to(device) # move data to device(cpu/cuda)
  with torch.no_grad(): # disable gradient calculation
    pred = model(x) # forward pass(compute output)
    loss = criterion(pred, y) # compute loss
  total_loss += loss.cpu().item() * len(x) # accumulate loss
  avg_loss = total_loss / len(dv.set.dataset()) # compute averaged loss

####5.8 Nerual NetWork Evaluation(Testing Set)

In [ ]:
model.eval() # set model to evaluation mode
preds = []
for x in tt_set: # iterate through the dataLoader
  x = x.to(device) # move data to device(cpu/cuda)
  with torch.no_grad(): # disable gradient calculation
    pred = model(x) # forward pass(compute output)
    preds.append(prd.cpu()) # collect prediction


####5.9 Save/Load a Nerual Network

In [ ]:
torch.save(model.state_dict(), path) # save
ckpt = torch.load(path) # load
model.load_state_dict(ckpt)